import Foundation

/// A very small synthesiser.
///
/// Every sound in the app is generated by this rather than loaded from a file. That is
/// not a purity exercise — it means sounds can be *pitched per character* at the point
/// of use, so Pip squeaks and Bramble rumbles out of the same bank, and it means there
/// is no audio to license before shipping.
///
/// Pure maths over a `[Float]`; no AVFoundation, no allocation beyond the buffer.
enum Synth {

    static let sampleRate: Double = 44_100

    /// Exponential decay — the shape almost every short percussive sound wants.
    static func decay(_ t: Double, _ duration: Double, attack: Double = 0.004, power: Double = 4) -> Double {
        if t < attack { return t / attack }
        let x = ((t - attack) / (duration - attack)).clamped(to: 0...1)
        return pow(1 - x, power)
    }

    /// A gentle swell, for sounds that are moved air rather than an impact.
    static func swell(_ t: Double, _ duration: Double) -> Double {
        let x = (t / duration).clamped(to: 0...1)
        return sin(x * .pi)
    }

    /// Render a tone whose frequency and amplitude are functions of time.
    static func tone(duration: Double,
                     frequency: (Double) -> Double,
                     amplitude: (Double) -> Double,
                     harmonic: Double = 0) -> [Float] {
        let count = Int(duration * sampleRate)
        var samples = [Float](repeating: 0, count: max(count, 1))
        var phase = 0.0
        for i in 0..<count {
            let t = Double(i) / sampleRate
            let f = max(frequency(t), 1)
            phase += 2 * .pi * f / sampleRate
            var value = sin(phase)
            // A little second harmonic stops a pure sine sounding like a hearing test.
            if harmonic > 0 { value += sin(phase * 2) * harmonic }
            samples[i] = Float(value * amplitude(t) / (1 + harmonic))
        }
        return samples
    }

    /// Render filtered noise. `colour` is a one-pole low-pass coefficient, 0…1, where
    /// lower is darker.
    static func noise(duration: Double,
                      colour: (Double) -> Double,
                      amplitude: (Double) -> Double,
                      seed: UInt64 = 0x9E3779B9) -> [Float] {
        let count = Int(duration * sampleRate)
        var samples = [Float](repeating: 0, count: max(count, 1))
        var state: UInt64 = seed
        var previous = 0.0
        for i in 0..<count {
            let t = Double(i) / sampleRate
            state ^= state << 13; state ^= state >> 7; state ^= state << 17
            let white = Double(Int64(bitPattern: state)) / Double(Int64.max)
            let k = colour(t).clamped(to: 0.001...1)
            previous += (white - previous) * k
            samples[i] = Float(previous * amplitude(t))
        }
        return samples
    }

    static func mix(_ tracks: [[Float]]) -> [Float] {
        let length = tracks.map(\.count).max() ?? 0
        var out = [Float](repeating: 0, count: length)
        for track in tracks {
            for i in 0..<track.count { out[i] += track[i] }
        }
        return out
    }

    /// Place `samples` at `offset` seconds inside a buffer of `duration` seconds.
    static func at(_ offset: Double, _ samples: [Float], duration: Double) -> [Float] {
        var out = [Float](repeating: 0, count: Int(duration * sampleRate))
        let start = Int(offset * sampleRate)
        for i in 0..<samples.count where start + i < out.count {
            out[start + i] = samples[i]
        }
        return out
    }

    /// Keep the result inside [-1, 1] without clipping artefacts.
    static func normalised(_ samples: [Float], peak: Float = 0.9) -> [Float] {
        guard let maximum = samples.map(abs).max(), maximum > 0 else { return samples }
        let scale = peak / maximum
        return samples.map { $0 * scale }
    }
}
